### PR TITLE
340/links to dates on numbers page is wrong

### LINKED ISSUE #340: Links to dates on numbers page is wrong
Query param should be `fecha` instead of `d` and should also include `dias`.

### PR DESCRIPTION
**Pull request by MauricioRobayo**
closes #340

### CODE REVIEW

File: components/NumbersData/NumbersData.tsx [hunk 1]
```diff
@@ -108,10 +111,15 @@ export default function NumbersPage({
...
                   <Link
-                    href={`/${citySlug}/${categoryData.slug}?d=${format(
-                      dataDate,
-                      "yyyy-MM-dd"
-                    )}`}
+                    href={{
+                      pathname: "/[city]/[category]",
+                      query: {
+                        city: query.city,
+                        category: query.category,
```
Comment (MauricioRobayo) [inline components/NumbersData/NumbersData.tsx]: Are we using `citySlug` or `categorySlug`? we could simplify props if getting this from `router.query`.

**Review by MauricioRobayo — COMMENTED** [review]
lgtm
